const gradeLevel = [
    { label: '小学一年级', value: 1 },
    { label: '小学二年级', value: 2 },
    { label: '小学三年级', value: 3 },
    { label: '小学四年级', value: 4 },
    { label: '小学五年级', value: 5 },
    { label: '小学六年级', value: 6 },
    { label: '初中一年级', value: 7 },
    { label: '初中二年级', value: 8 },
    { label: '初中三年级', value: 9 },
    { label: '高中一年级', value: 10 },
    { label: '高中二年级', value: 11 },
    { label: '高中三年级', value: 12 },
    { label: '专科一年级', value: 13 },
    { label: '专科二年级', value: 14 },
    { label: '专科三年级', value: 15 },
    { label: '本科一年级', value: 16 },
    { label: '本科二年级', value: 17 },
    { label: '本科三年级', value: 18 },
    { label: '本科四年级', value: 19 },
    { label: '硕士一年级', value: 20 },
    { label: '硕士二年级', value: 21 },
    { label: '硕士三年级', value: 22 },
    { label: '博士一年级', value: 23 },
    { label: '博士二年级', value: 24 },
    { label: '博士三年级', value: 25 },
    { label: '博士四年级', value: 26 },
    { label: '博士五年级', value: 27 },
]

export default gradeLevel
